"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "en" | "tr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  mounted: boolean;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    loading: "Loading...",
    error: "Error",
    refresh: "Refresh",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    logout: "Logout",
    home: "Home",
    actions: "Actions",
    created: "Created",
    noData: "No data found",

    // Header
    adminDashboard: "Admin Dashboard",
    instructorDashboard: "Instructor Dashboard",

    // Navigation
    organization: "Organization",
    classes: "Classes",
    sessions: "Sessions",
    bookings: "Bookings",
    members: "Members",
    instructors: "Instructors",
    users: "Users",

    // Users
    name: "Name",
    email: "Email",
    password: "Password",
    login: "Login",
    signIn: "Sign In",
    signingIn: "Signing in...",
    redirecting: "Redirecting...",
    failedToSignIn: "Failed to sign in",
    role: "Role",
    memberships: "Memberships",
    addUser: "Add User",
    addInstructor: "Add Instructor",
    createNewInstructor: "Create New Instructor",
    createNewInstructorDescription:
      "Create a new instructor account. An invitation email will be sent to the provided email address so they can set up their password and access the system.",
    createAndSendInvite: "Create & Send Invite",
    emailPlaceholder: "instructor@example.com",
    fullNamePlaceholder: "Full Name",
    noName: "No name",
    noUsersFound: "No users found",
    invitationStatus: "Invitation Status",
    checking: "Checking...",
    confirmed: "Confirmed",
    pending: "Pending",
    unknown: "Unknown",
    resendInvitation: "Resend Invitation",
    sending: "Sending...",
    resendInvitationConfirm: "Resend invitation email to {email}?",
    invitationSent: "Invitation sent successfully!",
    resetPassword: "Reset Password",
    resetting: "Sending...",
    resetPasswordConfirm: "Send password reset email to {email}?",
    passwordResetSent: "Password reset email sent successfully!",
    resetLink: "Reset Link",
    resetLinkCopied: "Reset link copied to clipboard!",
    resetLinkNote:
      "(Link has been copied to clipboard. Share it with the user if email is not received)",

    // Instructors
    status: "Status",
    bio: "Bio",
    specialties: "Specialties",
    noBio: "No bio",
    none: "None",
    noInstructorsFound: "No instructors found",
    active: "Active",
    inactive: "Inactive",
    editInstructor: "Edit Instructor",
    saving: "Saving...",
    deleting: "Deleting...",
    deleteConfirm:
      "Are you sure you want to delete this instructor? This action cannot be undone.",
    specialtiesPlaceholder: "Cycling, Yoga, Pilates",
    specialtiesCommaSeparated: "Specialties (comma-separated)",
    instructorBioPlaceholder: "Instructor bio...",

    // Instructor Dashboard
    welcome: "Welcome",
    instructorInformation: "Instructor Information",
    noAdditionalInfo: "No additional information available.",

    // Theme
    dark: "Dark",
    light: "Light",

    // Organization
    editOrganization: "Edit Organization",
    basicInformation: "Basic Information",
    contactInformation: "Contact Information",
    socialMedia: "Social Media",
    socialMediaLinks: "Social Media Links",
    statistics: "Statistics",
    slug: "Slug",
    description: "Description",
    phone: "Phone",
    address: "Address",
    website: "Website",
    facebook: "Facebook",
    twitter: "Twitter",
    instagram: "Instagram",
    linkedin: "LinkedIn",
    tiktok: "TikTok",
    latitude: "Latitude",
    longitude: "Longitude",
    location: "Location",
    failedToFetchOrganization: "Failed to fetch organization",
    failedToUpdateOrganization: "Failed to update organization",
    organizationUpdatedSuccessfully: "Organization updated successfully",
    // SMTP Configuration
    smtpConfiguration: "SMTP Configuration",
    smtpConfigurationDescription:
      "Configure SMTP settings for sending password reset emails. If not configured, environment variables will be used as fallback.",
    smtpHost: "SMTP Host",
    smtpPort: "SMTP Port",
    smtpUser: "SMTP User",
    smtpPassword: "SMTP Password",
    smtpFromEmail: "From Email",
    smtpFromName: "From Name",
    leaveBlankToKeepCurrent: "Leave blank to keep current password",
    language: "Language",
    emailLanguage: "Email Language",
    languageDescription:
      "Select the language for sending emails to users (password reset, invitations, etc.).",
    english: "English",
    turkish: "Turkish",
    // Invitation
    acceptInvitation: "Accept Invitation",
    setPasswordDescription:
      "Please set a password to complete your account setup.",
    waitingForInvitation: "Processing invitation link...",
    passwordSetSuccess: "Password Set Successfully!",
    redirectingToLogin: "Redirecting to login...",
    setting: "Setting...",
    setPassword: "Set Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",

    // Data List
    found: "Found",
    noDataAvailable: "No data available",
    foundItems: "Found {count} {item}",

    // Classes
    newClass: "New Class",
    createNewClass: "Create New Class",
    editClass: "Edit Class",
    createClass: "Create Class",
    allClasses: "All Classes",
    noClassesFound: "No classes found",

    // Members
    newMember: "New Member",
    createNewMember: "Create New Member",
    editMember: "Edit Member",
    createMember: "Create Member",
    noMembersFound: "No members found",
    membershipType: "Membership Type",
    membershipTypePlaceholder: "e.g., Premium, Basic, Monthly",
    selectUser: "Select User",
    noAvailableUsers: "No available users. All users are already members.",
    user: "User",
    member: "Member",
    confirmDelete:
      "Are you sure you want to delete this member? This action cannot be undone.",
    createNewUser: "Create New User",
    isRequired: "is required",
    memberCreatedSuccessfully: "Member created successfully",
    memberUpdatedSuccessfully: "Member updated successfully",
    memberDeletedSuccessfully: "Member deleted successfully",
    creditBalance: "Credit Balance",
    resetPasswordNote: "A password reset email will be sent to this user.",
    resendInvitationNote: "A new invitation email will be sent to this user.",
    deleteMember: "Delete Member",
    deleteInstructor: "Delete Instructor",
    deleteWarning: "This action cannot be undone.",
    creditTransactionHistory: "Credit Transaction History",
    viewHistory: "History",
    noTransactions: "No transactions found",
    date: "Date",
    type: "Type",
    amount: "Amount",
    balanceBefore: "Balance Before",
    balanceAfter: "Balance After",
    performedBy: "Performed By",
    adjustCreditBalance: "Adjust Credit Balance",
    creditChange: "Credit Change",
    positiveToAdd: "Positive to add",
    negativeToDeduct: "Negative to deduct",
    currentBalance: "Current Balance",
    newBalance: "New Balance",
    transactionDescriptionPlaceholder:
      "e.g., Payment received, Refund, Adjustment",
    duration: "Duration",
    minutes: "minutes",
    capacity: "Capacity",
    maxCapacity: "Max Capacity",
    instructor: "Instructor",
    optional: "optional",
    selectInstructor: "Select Instructor",
    archived: "Archived",

    // Sessions
    newSession: "New Session",
    createNewSession: "Create New Session",
    editSession: "Edit Session",
    createSession: "Create Session",
    allSessions: "All Sessions",
    noSessionsFound: "No sessions found",
    class: "Class",
    startTime: "Start Time",
    endTime: "End Time",
    currentBookings: "Current Bookings",
    scheduled: "Scheduled",
    inProgress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    selectClass: "Select Class",

    // Pricing
    pricing: "Pricing",
    creditPrice: "Credit Price",
    currency: "Currency",
    priceChangeReason: "Price Change Reason",
    priceChangeReasonPlaceholder:
      "e.g., Seasonal adjustment, Market rate change",
    viewPriceHistory: "View Price History",
    hidePriceHistory: "Hide Price History",
    priceHistory: "Price History",
    noPriceHistory: "No price history available.",
    creditPriceBefore: "Credit Price Before",
    creditPriceAfter: "Credit Price After",
    currencyBefore: "Currency Before",
    currencyAfter: "Currency After",
    changedBy: "Changed By",
    changedOn: "Changed On",
    effectiveFrom: "Effective From",
    effectiveUntil: "Effective Until",
    pricePeriodStart: "Price Period Start",
    pricePeriodEnd: "Price Period End",
    indefinite: "Indefinite",
    reason: "Reason",
    // Locations
    locations: "Locations",
    location: "Location",
    addLocation: "Add Location",
    editLocation: "Edit Location",
    deleteLocation: "Delete Location",
    locationName: "Location Name",
    locationDescription: "Description",
    locationAddress: "Address",
    defaultLocation: "Default Location",
    setAsDefault: "Set as Default",
    selectLocation: "Select Location",
    isDefault: "Is Default",
    // Seat Layouts
    seatLayouts: "Seat Layouts",
    seatLayout: "Seat Layout",
    addSeatLayout: "Add Seat Layout",
    editSeatLayout: "Edit Seat Layout",
    deleteSeatLayout: "Delete Seat Layout",
    layoutName: "Layout Name",
    layoutDescription: "Description",
    activeLayout: "Active Layout",
    // Seats
    seats: "Seats",
    seat: "Seat",
    addSeat: "Add Seat",
    editSeat: "Edit Seat",
    deleteSeat: "Delete Seat",
    seatNumber: "Seat Number",
    seatRow: "Row",
    seatColumn: "Column",
    seatType: "Seat Type",
    normalSeat: "Normal",
    exclusiveSeat: "Exclusive",
    creditCost: "Credit Cost",
    seatPosition: "Position",
    seatX: "X Position",
    seatY: "Y Position",
    selectSeat: "Select Seat",
    noSeatSelected: "No Seat Selected",
    updated: "Updated",
    deleted: "Deleted",
    successfully: "Successfully",
    addSeat: "Add Seat",
    editSeat: "Edit Seat",
    deleteSeat: "Delete Seat",
    row: "Row",
    column: "Column",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    credits: "Credits",
    exclusiveSeatInfo:
      "Exclusive seats are premium seats with higher credit cost.",
    normalSeatInfo: "Normal seats have standard credit cost.",
    creditCostHelp: "Number of credits required to book this seat",

    // Packages
    packages: "Packages",
    package: "Package",
    addPackage: "Add Package",
    editPackage: "Edit Package",
    deletePackage: "Delete Package",
    packageName: "Package Name",
    packageCode: "Package Code",
    packageType: "Package Type",
    packagePrice: "Price",
    packageCredits: "Credits",
    packageDescription: "Description",
    packageBenefits: "Benefits",
    basePrice: "Base Price",
    discountAmount: "Discount Amount",
    discountPercentage: "Discount Percentage",
    pricePerCredit: "Price Per Credit",
    singleRide: "Single Ride",
    creditPack: "Credit Pack",
    elite30: "Elite 30",
    allAccess: "All Access",
    redeemPackage: "Purchase Package",
    redeemPackageForMember: "Purchase Package for Member",
    selectPackage: "Select Package",
    selectCoupon: "Select Coupon (Optional)",
    packageRedeemed: "Package successfully purchased",
    noPackagesFound: "No packages found",

    // Coupons
    coupons: "Coupons",
    coupon: "Coupon",
    addCoupon: "Add Coupon",
    editCoupon: "Edit Coupon",
    deleteCoupon: "Delete Coupon",
    couponCode: "Coupon Code",
    couponName: "Coupon Name",
    couponType: "Coupon Type",
    discountCoupon: "Discount Coupon",
    packageCoupon: "Package Coupon",
    creditBonusCoupon: "Credit Bonus",
    discountType: "Discount Type",
    percentage: "Percentage",
    fixedAmount: "Fixed Amount",
    discountValue: "Discount Value",
    applicablePackages: "Applicable Packages",
    bonusCredits: "Bonus Credits",
    maxRedemptions: "Max Redemptions",
    maxRedemptionsPerMember: "Max Per Member",
    validFrom: "Valid From",
    validUntil: "Valid Until",
    noCouponsFound: "No coupons found",

    // Redemptions
    redemptions: "Redemptions",
    redemption: "Redemption",
    redemptionType: "Redemption Type",
    redeemedAt: "Redeemed At",
    redeemedBy: "Redeemed By",
    originalPrice: "Original Price",
    finalPrice: "Final Price",
    creditsAdded: "Credits Added",
    allAccessExpiresAt: "All Access Expires At",
    friendPassAvailable: "Friend Pass Available",
    friendPassExpiresAt: "Friend Pass Expires At",
    friendPassUsed: "Friend Pass Used",
    viewRedemptions: "View Redemptions",
    noRedemptionsFound: "No redemptions found",
    // Redemptions Management
    redemptionsTitle: "Package Purchases",
    redemptionsPending: "Pending",
    redemptionsAll: "All Redemptions",
    redemptionsOrderId: "Order ID",
    redemptionsCustomer: "Customer",
    redemptionsPackage: "Package",
    redemptionsAmount: "Amount",
    redemptionsDate: "Date",
    redemptionsActions: "Actions",
    redemptionsCoupon: "Coupon",
    redemptionsNoPending: "No pending redemptions",
    redemptionsNoRedemptions: "No redemptions found",
    redemptionsConfirm: "Confirm",
    redemptionsReject: "Reject",
    redemptionsConfirmTitle: "Confirm Package Activation",
    redemptionsConfirmMessage:
      "Are you sure you want to confirm this package purchase and activate it for the customer?",
    redemptionsConfirmSuccess: "Package activated successfully",
    redemptionsConfirmError: "Failed to confirm redemption",
    redemptionsRejectTitle: "Reject Package Purchase",
    redemptionsRejectMessage:
      "Are you sure you want to reject this package purchase?",
    redemptionsRejectSuccess: "Redemption rejected successfully",
    redemptionsRejectError: "Failed to reject redemption",
    redemptionsReason: "Reason",
    redemptionsReasonPlaceholder: "Enter rejection reason...",
    redemptionsId: "ID",
    redemptionsMember: "Member",
    redemptionsPrice: "Price",
    redemptionsCredits: "Credits",
    redemptionsStatus: "Status",
    redemptionsOriginal: "Original",
    save: "Save",
    none: "None",
    details: "Details",
    optional: "Optional",
    customPrice: "Custom Price",
    processing: "Processing...",
    createdSuccessfully: "created successfully",
    updatedSuccessfully: "updated successfully",
    deletedSuccessfully: "deleted successfully",
    selectSeatLayout: "Please select a seat layout first",
    instructor: "Instructor",
    podium: "Podium",
    gridSize: "Grid Size",
    rows: "Rows",
    columns: "Columns",
    gridSizeHelp:
      "Optional: Define grid size (e.g., 3 rows x 4 columns = 3x4 grid)",
    instructorSeatInfo: "Instructor position - not bookable by members.",
    podiumSeatInfo: "Podium position - elevated platform area.",
    notBookable: "Not Bookable",
    grid: "Grid",
    maxRow: "Max Row",
    maxColumn: "Max Column",
    cannotExceed: "cannot exceed",
    rowHelp: "Enter row identifier (e.g., A, B, C or 1, 2, 3)",
    columnHelp: "Enter column number",
    // Spinning Frontend
    spinningApp: "Spinning Studio",
    purchase: "Purchase",
    bookNow: "Book Now",
    insufficientCredits: "Insufficient credits",
    purchasePackage: "Purchase Package",
    originalPrice: "Original Price",
    discount: "Discount",
    available: "available",
    friendPass: "Friend Pass",
    eliteMember: "Elite Member",
    expired: "Expired",
    booked: "booked",
    full: "Full",
    confirm: "Confirm",
    paymentMethod: "Payment Method",
  },
  tr: {
    // Common
    loading: "yükleniyor...",
    emailLanguage: "E-posta Dili",
    languageDescription:
      "Kullanıcılara gönderilecek e-postalar için dili seçin (şifre sıfırlama, davetiyeler vb.).",
    english: "İngilizce",
    turkish: "Türkçe",
    error: "Hata",
    refresh: "Yenile",
    save: "Kaydet",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    logout: "Çıkış",
    home: "Ana Sayfa",
    actions: "İşlemler",
    created: "Oluşturulma",
    noData: "Veri bulunamadı",

    // Header
    adminDashboard: "Yönetici Paneli",
    instructorDashboard: "Eğitmen Paneli",

    // Navigation
    organization: "Organizasyon",
    classes: "Sınıflar",
    sessions: "Oturumlar",
    bookings: "Rezervasyonlar",
    members: "Üyeler",
    instructors: "Eğitmenler",
    users: "Kullanıcılar",

    // Users
    name: "İsim",
    email: "E-posta",
    password: "Şifre",
    login: "Giriş",
    signIn: "Giriş Yap",
    signingIn: "Giriş yapılıyor...",
    redirecting: "Yönlendiriliyor...",
    failedToSignIn: "Giriş başarısız",
    role: "Rol",
    memberships: "Üyelikler",
    addUser: "Kullanıcı Ekle",
    addInstructor: "Eğitmen Ekle",
    createNewInstructor: "Yeni Eğitmen Oluştur",
    createNewInstructorDescription:
      "Yeni bir eğitmen hesabı oluşturun. Sağlanan e-posta adresine davet e-postası gönderilecek, böylece şifrelerini ayarlayıp sisteme erişebilirler.",
    createAndSendInvite: "Oluştur ve Davetiye Gönder",
    emailPlaceholder: "egitmen@ornek.com",
    fullNamePlaceholder: "Ad Soyad",
    noName: "İsim yok",
    noUsersFound: "Kullanıcı bulunamadı",
    invitationStatus: "Davet Durumu",
    checking: "Kontrol ediliyor...",
    confirmed: "Onaylandı",
    pending: "Beklemede",
    unknown: "Bilinmiyor",
    resendInvitation: "Davetiye Yeniden Gönder",
    sending: "Gönderiliyor...",
    resendInvitationConfirm:
      "{email} adresine davetiye e-postasını yeniden gönder?",
    invitationSent: "Davetiye başarıyla gönderildi!",
    resetPassword: "Şifre Sıfırla",
    resetting: "Gönderiliyor...",
    resetPasswordConfirm: "{email} adresine şifre sıfırlama e-postası gönder?",
    passwordResetSent: "Şifre sıfırlama e-postası başarıyla gönderildi!",
    resetLink: "Sıfırlama Bağlantısı",
    resetLinkCopied: "Sıfırlama bağlantısı panoya kopyalandı!",
    resetLinkNote:
      "(Bağlantı panoya kopyalandı. E-posta alınmadıysa kullanıcıyla paylaşın)",

    // Instructors
    status: "Durum",
    bio: "Biyografi",
    specialties: "Uzmanlık Alanları",
    noBio: "Biyografi yok",
    none: "Yok",
    noInstructorsFound: "Eğitmen bulunamadı",
    active: "Aktif",
    inactive: "Pasif",
    editInstructor: "Eğitmeni Düzenle",
    saving: "Kaydediliyor...",
    deleting: "Siliniyor...",
    deleteConfirm:
      "Bu eğitmeni silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    specialtiesPlaceholder: "Bisiklet, Yoga, Pilates",
    specialtiesCommaSeparated: "Uzmanlık Alanları (virgülle ayrılmış)",
    instructorBioPlaceholder: "Eğitmen biyografisi...",

    // Instructor Dashboard
    welcome: "Hoş geldiniz",
    instructorInformation: "Eğitmen Bilgileri",
    noAdditionalInfo: "Ek bilgi mevcut değil.",

    // Theme
    dark: "Karanlık",
    light: "Aydınlık",

    // Organization
    editOrganization: "Organizasyonu Düzenle",
    basicInformation: "Temel Bilgiler",
    contactInformation: "İletişim Bilgileri",
    socialMedia: "Sosyal Medya",
    socialMediaLinks: "Sosyal Medya Bağlantıları",
    statistics: "İstatistikler",
    slug: "Kısa Ad",
    description: "Açıklama",
    phone: "Telefon",
    address: "Adres",
    website: "Web Sitesi",
    facebook: "Facebook",
    twitter: "Twitter",
    instagram: "Instagram",
    linkedin: "LinkedIn",
    tiktok: "TikTok",
    latitude: "Enlem",
    longitude: "Boylam",
    location: "Konum",
    // SMTP Configuration
    smtpConfiguration: "SMTP Yapılandırması",
    smtpConfigurationDescription:
      "Şifre sıfırlama e-postalarını göndermek için SMTP ayarlarını yapılandırın. Yapılandırılmazsa, ortam değişkenleri yedek olarak kullanılacaktır.",
    smtpHost: "SMTP Sunucusu",
    smtpPort: "SMTP Port",
    smtpUser: "SMTP Kullanıcı",
    smtpPassword: "SMTP Şifre",
    smtpFromEmail: "Gönderen E-posta",
    smtpFromName: "Gönderen İsim",
    leaveBlankToKeepCurrent: "Mevcut şifreyi korumak için boş bırakın",
    language: "Dil",
    // Invitation
    acceptInvitation: "Daveti Kabul Et",
    setPasswordDescription:
      "Hesap kurulumunuzu tamamlamak için lütfen bir şifre belirleyin.",
    waitingForInvitation: "Davet bağlantısı işleniyor...",
    passwordSetSuccess: "Şifre Başarıyla Ayarlandı!",
    redirectingToLogin: "Giriş sayfasına yönlendiriliyor...",
    setting: "Ayarlandı...",
    setPassword: "Şifre Belirle",
    newPassword: "Yeni Şifre",
    confirmPassword: "Şifreyi Onayla",
    failedToFetchOrganization: "Organizasyon bilgisi alınamadı",
    failedToUpdateOrganization: "Organizasyon güncellenemedi",
    organizationUpdatedSuccessfully: "Organizasyon başarıyla güncellendi",

    // Data List
    found: "Bulundu",
    noDataAvailable: "Veri mevcut değil",
    foundItems: "{count} {item} bulundu",

    // Classes
    newClass: "Yeni Sınıf",
    createNewClass: "Yeni Sınıf Oluştur",
    editClass: "Sınıfı Düzenle",
    createClass: "Sınıf Oluştur",
    allClasses: "Tüm Sınıflar",
    noClassesFound: "Sınıf bulunamadı",

    // Members
    newMember: "Yeni Üye",
    createNewMember: "Yeni Üye Oluştur",
    editMember: "Üyeyi Düzenle",
    createMember: "Üye Oluştur",
    noMembersFound: "Üye bulunamadı",
    membershipType: "Üyelik Türü",
    membershipTypePlaceholder: "örn: Premium, Temel, Aylık",
    selectUser: "Kullanıcı Seç",
    noAvailableUsers: "Mevcut kullanıcı yok. Tüm kullanıcılar zaten üye.",
    user: "Kullanıcı",
    member: "Üye",
    confirmDelete:
      "Bu üyeyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
    createNewUser: "Yeni Kullanıcı Oluştur",
    isRequired: "zorunludur",
    memberCreatedSuccessfully: "Üye başarıyla oluşturuldu",
    memberUpdatedSuccessfully: "Üye başarıyla güncellendi",
    memberDeletedSuccessfully: "Üye başarıyla silindi",
    creditBalance: "Kredi Bakiyesi",
    creditTransactionHistory: "Kredi İşlem Geçmişi",
    viewHistory: "Geçmiş",
    noTransactions: "İşlem bulunamadı",
    date: "Tarih",
    type: "Tür",
    amount: "Tutar",
    balanceBefore: "Önceki Bakiye",
    balanceAfter: "Sonraki Bakiye",
    performedBy: "İşlemi Yapan",
    adjustCreditBalance: "Kredi Bakiyesini Ayarla",
    creditChange: "Kredi Değişikliği",
    positiveToAdd: "Pozitif ekle",
    negativeToDeduct: "Negatif çıkar",
    currentBalance: "Mevcut Bakiye",
    newBalance: "Yeni Bakiye",
    transactionDescriptionPlaceholder: "örn: Ödeme alındı, İade, Düzeltme",

    duration: "Süre",
    minutes: "dakika",
    capacity: "Kapasite",
    maxCapacity: "Maksimum Kapasite",
    instructor: "Eğitmen",
    optional: "isteğe bağlı",
    selectInstructor: "Eğitmen Seç",
    archived: "Arşivlendi",

    // Sessions
    newSession: "Yeni Oturum",
    createNewSession: "Yeni Oturum Oluştur",
    editSession: "Oturumu Düzenle",
    createSession: "Oturum Oluştur",
    allSessions: "Tüm Oturumlar",
    noSessionsFound: "Oturum bulunamadı",
    class: "Sınıf",
    startTime: "Başlangıç Zamanı",
    endTime: "Bitiş Zamanı",
    currentBookings: "Mevcut Rezervasyonlar",
    scheduled: "Planlandı",
    inProgress: "Devam Ediyor",
    completed: "Tamamlandı",
    cancelled: "İptal Edildi",
    selectClass: "Sınıf Seç",

    // Pricing
    pricing: "Fiyatlandırma",
    creditPrice: "Kredi Fiyatı",
    currency: "Para Birimi",
    priceChangeReason: "Fiyat Değişiklik Nedeni",
    priceChangeReasonPlaceholder:
      "örn: Mevsimsel ayarlama, Piyasa fiyatı değişikliği",
    viewPriceHistory: "Fiyat Geçmişini Görüntüle",
    hidePriceHistory: "Fiyat Geçmişini Gizle",
    priceHistory: "Fiyat Geçmişi",
    noPriceHistory: "Fiyat geçmişi bulunmamaktadır.",
    creditPriceBefore: "Önceki Kredi Fiyatı",
    creditPriceAfter: "Sonraki Kredi Fiyatı",
    currencyBefore: "Önceki Para Birimi",
    currencyAfter: "Sonraki Para Birimi",
    changedBy: "Değiştiren",
    changedOn: "Değiştirilme Tarihi",
    effectiveFrom: "Geçerlilik Başlangıcı",
    effectiveUntil: "Geçerlilik Bitişi",
    pricePeriodStart: "Fiyat Dönemi Başlangıcı",
    pricePeriodEnd: "Fiyat Dönemi Bitişi",
    indefinite: "Belirsiz",
    reason: "Neden",
    // Locations
    locations: "Konumlar",
    location: "Konum",
    addLocation: "Konum Ekle",
    editLocation: "Konumu Düzenle",
    deleteLocation: "Konumu Sil",
    locationName: "Konum Adı",
    locationDescription: "Açıklama",
    locationAddress: "Adres",
    defaultLocation: "Varsayılan Konum",
    setAsDefault: "Varsayılan Olarak Ayarla",
    selectLocation: "Konum Seç",
    isDefault: "Varsayılan",
    // Seat Layouts
    seatLayouts: "Koltuk Düzenleri",
    seatLayout: "Koltuk Düzeni",
    addSeatLayout: "Koltuk Düzeni Ekle",
    editSeatLayout: "Koltuk Düzenini Düzenle",
    deleteSeatLayout: "Koltuk Düzenini Sil",
    layoutName: "Düzen Adı",
    layoutDescription: "Açıklama",
    activeLayout: "Aktif Düzen",
    // Seats
    seats: "Koltuklar",
    seat: "Koltuk",
    addSeat: "Koltuk Ekle",
    editSeat: "Koltuk Düzenle",
    deleteSeat: "Koltuk Sil",
    seatNumber: "Koltuk Numarası",
    seatRow: "Sıra",
    seatColumn: "Sütun",
    seatType: "Koltuk Tipi",
    normalSeat: "Normal",
    exclusiveSeat: "Özel",
    creditCost: "Kredi Maliyeti",
    seatPosition: "Pozisyon",
    seatX: "X Pozisyonu",
    seatY: "Y Pozisyonu",
    selectSeat: "Koltuk Seç",
    noSeatSelected: "Koltuk Seçilmedi",
    updated: "Güncellendi",
    deleted: "Silindi",
    successfully: "Başarıyla",
    addSeat: "Koltuk Ekle",
    editSeat: "Koltuk Düzenle",
    deleteSeat: "Koltuk Sil",
    row: "Sıra",
    column: "Sütun",
    status: "Durum",
    active: "Aktif",
    inactive: "Pasif",
    credits: "Kredi",
    exclusiveSeatInfo:
      "Özel koltuklar yüksek kredi maliyetli premium koltuklardır.",
    normalSeatInfo: "Normal koltuklar standart kredi maliyetine sahiptir.",
    creditCostHelp: "Bu koltuğu rezerve etmek için gereken kredi sayısı",

    // Packages
    packages: "Paketler",
    package: "Paket",
    addPackage: "Paket Ekle",
    editPackage: "Paketi Düzenle",
    deletePackage: "Paketi Sil",
    packageName: "Paket Adı",
    packageCode: "Paket Kodu",
    packageType: "Paket Türü",
    packagePrice: "Fiyat",
    packageCredits: "Kredi Sayısı",
    packageDescription: "Açıklama",
    packageBenefits: "Avantajlar",
    basePrice: "Taban Fiyat",
    discountAmount: "İndirim Tutarı",
    discountPercentage: "İndirim Yüzdesi",
    pricePerCredit: "Kredi Başına Fiyat",
    singleRide: "Tek Sürüş",
    creditPack: "Kredi Paketi",
    elite30: "Elite 30",
    allAccess: "All Access",
    redeemPackage: "Paket Satın Al",
    redeemPackageForMember: "Üye İçin Paket Satın Al",
    selectPackage: "Paket Seç",
    selectCoupon: "Kupon Seç (İsteğe Bağlı)",
    packageRedeemed: "Paket başarıyla satın alındı",
    noPackagesFound: "Paket bulunamadı",

    // Coupons
    coupons: "Kuponlar",
    coupon: "Kupon",
    addCoupon: "Kupon Ekle",
    editCoupon: "Kuponu Düzenle",
    deleteCoupon: "Kuponu Sil",
    couponCode: "Kupon Kodu",
    couponName: "Kupon Adı",
    couponType: "Kupon Türü",
    discountCoupon: "İndirim Kuponu",
    packageCoupon: "Paket Kuponu",
    creditBonusCoupon: "Kredi Bonusu",
    discountType: "İndirim Türü",
    percentage: "Yüzde",
    fixedAmount: "Sabit Tutar",
    discountValue: "İndirim Değeri",
    applicablePackages: "Uygulanabilir Paketler",
    bonusCredits: "Bonus Kredi",
    maxRedemptions: "Maksimum Kullanım",
    maxRedemptionsPerMember: "Üye Başına Maksimum",
    validFrom: "Geçerlilik Başlangıcı",
    validUntil: "Geçerlilik Bitişi",
    noCouponsFound: "Kupon bulunamadı",

    // Redemptions
    redemptions: "Satın Alımlar",
    redemption: "Satın Alım",
    redemptionType: "Satın Alım Türü",
    redeemedAt: "Satın Alım Tarihi",
    redeemedBy: "Satın Alan",
    originalPrice: "Orijinal Fiyat",
    finalPrice: "Ödenen Fiyat",
    creditsAdded: "Eklenen Kredi",
    allAccessExpiresAt: "All Access Bitiş Tarihi",
    friendPassAvailable: "Arkadaş Hakkı Mevcut",
    friendPassExpiresAt: "Arkadaş Hakkı Bitiş Tarihi",
    friendPassUsed: "Arkadaş Hakkı Kullanıldı",
    viewRedemptions: "Satın Alımları Görüntüle",
    noRedemptionsFound: "Satın alım bulunamadı",
    // Redemptions Management
    redemptionsTitle: "Paket Satın Alımları",
    redemptionsPending: "Bekleyen",
    redemptionsAll: "Tüm Satın Alımlar",
    redemptionsOrderId: "Sipariş No",
    redemptionsCustomer: "Müşteri",
    redemptionsPackage: "Paket",
    redemptionsAmount: "Tutar",
    redemptionsDate: "Tarih",
    redemptionsActions: "İşlemler",
    redemptionsCoupon: "Kupon",
    redemptionsNoPending: "Bekleyen satın alım yok",
    redemptionsNoRedemptions: "Satın alım bulunamadı",
    redemptionsConfirm: "Onayla",
    redemptionsReject: "Reddet",
    redemptionsConfirmTitle: "Paket Aktivasyonunu Onayla",
    redemptionsConfirmMessage:
      "Bu paket satın alımını onaylayıp müşteri için aktifleştirmek istediğinizden emin misiniz?",
    redemptionsConfirmSuccess: "Paket başarıyla aktifleştirildi",
    redemptionsConfirmError: "Satın alım onaylanamadı",
    redemptionsRejectTitle: "Paket Satın Alımını Reddet",
    redemptionsRejectMessage:
      "Bu paket satın alımını reddetmek istediğinizden emin misiniz?",
    redemptionsRejectSuccess: "Satın alım başarıyla reddedildi",
    redemptionsRejectError: "Satın alım reddedilemedi",
    redemptionsReason: "Neden",
    redemptionsReasonPlaceholder: "Reddetme nedeni girin...",
    redemptionsId: "ID",
    redemptionsMember: "Üye",
    redemptionsPrice: "Fiyat",
    redemptionsCredits: "Kredi",
    redemptionsStatus: "Durum",
    redemptionsOriginal: "Orijinal",
    save: "Tasarruf",
    none: "Yok",
    details: "Detaylar",
    optional: "İsteğe Bağlı",
    customPrice: "Özel Fiyat",
    processing: "İşleniyor...",
    createdSuccessfully: "başarıyla oluşturuldu",
    updatedSuccessfully: "başarıyla güncellendi",
    deletedSuccessfully: "başarıyla silindi",
    selectSeatLayout: "Lütfen önce bir koltuk düzeni seçin",
    instructor: "Eğitmen",
    podium: "Podyum",
    gridSize: "Grid Boyutu",
    rows: "Satırlar",
    columns: "Sütunlar",
    gridSizeHelp:
      "Opsiyonel: Grid boyutunu tanımlayın (örn: 3 satır x 4 sütun = 3x4 grid)",
    instructorSeatInfo:
      "Eğitmen pozisyonu - üyeler tarafından rezerve edilemez.",
    podiumSeatInfo: "Podyum pozisyonu - yükseltilmiş platform alanı.",
    architecturalColumn: "Mimari Sütun",
    architecturalColumnInfo: "Mimari sütun - yapısal eleman, rezerve edilemez.",
    notBookable: "Rezerve Edilemez",
    grid: "Grid",
    maxRow: "Maksimum Sıra",
    maxColumn: "Maksimum Sütun",
    cannotExceed: "aşamaz",
    rowHelp: "Sıra tanımlayıcısı girin (örn: A, B, C veya 1, 2, 3)",
    columnHelp: "Sütun numarası girin",
    // Spinning Frontend
    spinningApp: "Spinning Stüdyo",
    purchase: "Satın Al",
    bookNow: "Şimdi Rezerve Et",
    insufficientCredits: "Yetersiz kredi",
    purchasePackage: "Paket Satın Al",
    originalPrice: "Orijinal Fiyat",
    discount: "İndirim",
    available: "mevcut",
    friendPass: "Arkadaş Hakkı",
    eliteMember: "Elite Üye",
    expired: "Süresi Doldu",
    booked: "rezerve edildi",
    full: "Dolu",
    confirm: "Onayla",
    paymentMethod: "Ödeme Yöntemi",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Get language from localStorage or default to English
    const savedLanguage = localStorage.getItem("language") as Language | null;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "tr")) {
      setLanguageState(savedLanguage);
    }
  }, []);

  useEffect(() => {
    if (!mounted) return;

    // Save to localStorage
    localStorage.setItem("language", language);

    // Dispatch custom event so components can listen
    window.dispatchEvent(
      new CustomEvent("language-change", { detail: language })
    );
  }, [language, mounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, mounted }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
